version: '3.8'

services:
  web:
    build: ./services/flaskAPI
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./services/flaskAPI/:/usr/src/app/
    ports:
      - 5001:5001
    env_file:
      - ./.env.dev