version: '3.8'

services:
  flaskapi:
    build: 
      context: ./services/flaskAPI
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5001 app:app
    expose:
      - 5001
    env_file:
      - ./.env.dev
    volumes:
      - /mycontainer:/services/flaskAPI/

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - flaskapi